#!/usr/bin/env bash
# Regenerate the Homebrew formula for a tagged release and push it to the tap.
#
# Run from a release build, after `make dist`, with dist/checksums.txt present.
# The formula pins each asset by SHA256, so it must be generated after the
# assets exist rather than hand-maintained.
set -euo pipefail

VERSION="${1:?usage: update-tap.sh vX.Y.Z}"
VERSION_NO_V="${VERSION#v}"
REPO="${REPO:-mcavage/dk-cli}"
TAP_REPO="${TAP_REPO:-mcavage/homebrew-tap}"

sha() { awk -v a="dk_$1" '$2 == a {print $1}' dist/checksums.txt; }

DARWIN_ARM64="$(sha darwin_arm64)"
DARWIN_AMD64="$(sha darwin_amd64)"
LINUX_AMD64="$(sha linux_amd64)"
LINUX_ARM64="$(sha linux_arm64)"

for v in DARWIN_ARM64 DARWIN_AMD64 LINUX_AMD64 LINUX_ARM64; do
  [ -n "${!v}" ] || { echo "missing checksum for $v" >&2; exit 1; }
done

BASE="https://github.com/${REPO}/releases/download/${VERSION}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git clone --depth 1 "https://x-access-token:${TAP_TOKEN}@github.com/${TAP_REPO}.git" "$WORK/tap"
mkdir -p "$WORK/tap/Formula"

cat > "$WORK/tap/Formula/dk.rb" <<RUBY
# Generated by scripts/update-tap.sh. Do not edit by hand.
class Dk < Formula
  desc "Agent-first CLI for DigiKey: price a BOM, hand off a cart"
  homepage "https://github.com/${REPO}"
  version "${VERSION_NO_V}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/dk_darwin_arm64"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "${BASE}/dk_darwin_amd64"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/dk_linux_arm64"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${BASE}/dk_linux_amd64"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install Dir["dk_*"].first => "dk"
  end

  test do
    # version needs no credentials and no network, so the bottle test is real
    # rather than a smoke test that passes on a broken binary.
    assert_match "ok", shell_output("#{bin}/dk version")
  end
end
RUBY

cd "$WORK/tap"
git config user.name "dk release"
git config user.email "noreply@github.com"
git add Formula/dk.rb
git commit -m "dk ${VERSION}"
git push
